# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('group', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('forename', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Teacher'),
        ),
    ]
